'use client'

import { useState } from 'react'
import { ArrowDown, ArrowUpRight, Menu, RotateCcw, Sparkles, X } from 'lucide-react'

const jewelry = [
  ['Emerald Christmas Lady', 'Victorian sticker · winter salon', 'A luxurious die-cut portrait in emerald velvet, gold embroidery, and candlelight.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_a_luxurious_die-cut_sticker_of_a_Victorian__b82a7e53-932a-402b-befd-d8785cb6bcb5_3-zMoBeMlqJ9LCvC1l6Ec62ALW5WJdfH.png'],
  ['Lantern Keeper', 'Victorian sticker · evening garden', 'A romantic green-gowned figure carrying a glowing antique lantern through snow-covered branches.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_a_luxurious_die-cut_sticker_of_a_Victorian__b82a7e53-932a-402b-befd-d8785cb6bcb5_2-a8oBXWWKZov98F76G6e06sd3zEKx9Y.png'],
  ['Winter Garden Muse', 'Victorian sticker · frosted pine', 'A richly embellished emerald gown framed by frost, warm light, and evergreen shadows.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_a_luxurious_die-cut_sticker_of_a_Victorian__b82a7e53-932a-402b-befd-d8785cb6bcb5_1-b8ZjCmUQE7axPS6EtGdNVkVO9g7VSc.png'],
  ['Golden Lantern Portrait', 'Victorian sticker · twilight collection', 'A classic Victorian silhouette with a glowing lantern and softly gilded details.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_a_luxurious_die-cut_sticker_of_a_Victorian__b82a7e53-932a-402b-befd-d8785cb6bcb5_0-lVTKVlTZBb7fZ5vXj558qLIKrOmelb.png'],
] as const

const stickerNames = ['Botanical sprig', 'Perfume bottle', 'Paris label', 'Victorian rose']

const archiveImages = [
  ['Jewelry cabinet', 'A sunlit vanity with an open scrapbook and treasured pieces.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_a_cinematic_3D_vintage_atelier_for_a_jewelr_8a0e9e68-4dea-4a2a-8202-473f93a155bb_2-Nv0DhOADYC1fmY5IuBC9FbJTvflquZ.png'],
  ['The dressing room', 'A jewel box, mirror, and paper keepsakes gathered in warm light.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_a_cinematic_3D_vintage_atelier_for_a_jewelr_8a0e9e68-4dea-4a2a-8202-473f93a155bb_3-8z2NSzCKM4HGBXfZsEXYXoxiLkptFv.png'],
  ['Rosewood keepsake box', 'Vintage jewelry resting beside botanical correspondence.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_reate_a_wide_cinematic_website_hero_showing_an_ope_0021af75-1bfb-4b4a-8a9b-72f3faa5b585_3-TPj3I5scvJ9pvenef4IvzcizqwfXJI.png'],
  ['Open jewelry case', 'Gold pieces and illustrated cards arranged like a private collection.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_a_cinematic_3D_vintage_atelier_for_a_jewelr_8a0e9e68-4dea-4a2a-8202-473f93a155bb_0-qvLWZg9zekhzihkKti0qoBmAmTRMYd.png'],
  ['The collector’s drawer', 'A close study of chains, charms, and floral ephemera.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_reate_a_wide_cinematic_website_hero_showing_an_ope_0021af75-1bfb-4b4a-8a9b-72f3faa5b585_0-i6zI0FBjElbENIRT1vD4frrfgAeeQq.png'],
  ['Botanical correspondence', 'Pressed flowers and old-world jewelry tucked into a mahogany drawer.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_reate_a_wide_cinematic_website_hero_showing_an_ope_0021af75-1bfb-4b4a-8a9b-72f3faa5b585_2-5CGkG3mnCNeUuWBf20ks42D4T2J3na.png'],
  ['Winter promenade', 'A back-facing burgundy gown moving through a snow-covered woodland.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_a_Victorian_fashion_sticker_featuring_a_wom_df92d695-5a4e-46d0-b432-d28e6f2a1bef_3%20%281%29-7SazLyDK7sCGZJxocuU5Orw9VzRAdf.png'],
  ['The winter portrait', 'A Victorian figure in a high-collared velvet dress against frosted trees.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_a_Victorian_fashion_sticker_featuring_a_wom_df92d695-5a4e-46d0-b432-d28e6f2a1bef_2%20%281%29-f84YPXvchIfMUlTsJYzIf2DyDqR9pP.png'],
  ['Burgundy profile', 'A richly layered gown framed by a pale, snowy forest.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_a_Victorian_fashion_sticker_featuring_a_wom_df92d695-5a4e-46d0-b432-d28e6f2a1bef_0%20%281%29-FjxYivwXbiM8MK4MyKCvigafUSieDB.png'],
  ['Snowfall silhouette', 'A graceful rear view of the velvet dress with a crisp sticker edge.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_a_Victorian_fashion_sticker_featuring_a_wom_df92d695-5a4e-46d0-b432-d28e6f2a1bef_1%20%281%29-DRgp8FI1PXIQseNpU1iqDMWkWqJKs3.png'],
  ['Winter bride', 'An ivory satin gown and lace cape beneath snow-laden birch trees.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_Victorian_fantasy_sticker_of_an_elegant_w_e2efebe7-dc3e-4ad9-afcc-240a48c00296_3-YnN1Ytq7sRI8ZsiOxXao80OmB6r4DZ.png'],
  ['Birchwood bride', 'A crowned figure in a long embroidered cape walking through a pale winter grove.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_Victorian_fantasy_sticker_of_an_elegant_w_e2efebe7-dc3e-4ad9-afcc-240a48c00296_2-Xp2O5trpVwaoHWw7nntienCoF9fXVm.png'],
  ['Frosted lace', 'An elegant white lace cloak glowing among crystalline branches.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_Victorian_fantasy_sticker_of_an_elegant_w_e2efebe7-dc3e-4ad9-afcc-240a48c00296_0-pSuXwvX0HT1sLNBS0VZ2pqLdbonwVH.png'],
  ['Ivory procession', 'A warm winter portrait of a jeweled gown framed by snow-dusted trees.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_Victorian_fantasy_sticker_of_an_elegant_w_e2efebe7-dc3e-4ad9-afcc-240a48c00296_1-f6Xy0sofuJOB1IbMQYy0WSaOpjAJyB.png'],
  ['Ruby jewelry case', 'A burgundy velvet jewel box displaying ornate gold earrings and pearls.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_an_original_vintage_Avon-inspired_die-cut_s_64306f31-34e5-4ebd-b4ae-93fbf3020ecb_0-pU41YgKeG7keRV7fkjsm0ZOBTORrUo.png'],
  ['Pearl keepsake', 'A petite red velvet case holding a delicate gold-and-pearl pair.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_an_original_vintage_Avon-inspired_die-cut_s_64306f31-34e5-4ebd-b4ae-93fbf3020ecb_1-VipAWyZuolVzXAu0GQ2KJUnJS1kWD8.png'],
  ['Golden heirloom set', 'An open jewel box with an ornate brooch and matching pearl earrings.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_an_original_vintage_Avon-inspired_die-cut_s_64306f31-34e5-4ebd-b4ae-93fbf3020ecb_2-JFjanS1945YNdPe7R2WqiXvgGwkiRT.png'],
  ['Crimson jewelry box', 'A ruby-toned case presenting a classic gold brooch and pearl drops.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_an_original_vintage_Avon-inspired_die-cut_s_64306f31-34e5-4ebd-b4ae-93fbf3020ecb_3-2YNwX9Mj1yQN44yJHSfLpo2u6fA31w.png'],
  ['Violet perfume', 'An amber perfume bottle tied with ivory ribbon and violet blossoms.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_vintage_beauty_collectible_sticker_featur_01de2601-3f08-48d9-8bf6-319a0585b4b5_0-IqgEEah6fJO1Kz8bP1k7IFjMDVGgdh.png'],
  ['Floral perfume bottle', 'A glowing golden scent bottle surrounded by fresh purple violets.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_vintage_beauty_collectible_sticker_featur_01de2601-3f08-48d9-8bf6-319a0585b4b5_1-qZOLUUTPhiE4VtEzNvf5QGgR0ao4Bp.png'],
  ['Gilded scent', 'A vintage amber fragrance bottle nestled in a bed of violets.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_vintage_beauty_collectible_sticker_featur_01de2601-3f08-48d9-8bf6-319a0585b4b5_2-pkgZy3W5J6xDXI3OYKeuZE5JqbVR3x.png'],
  ['Lavender perfume', 'An ornate amber flacon with a soft lavender-toned backdrop.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_vintage_beauty_collectible_sticker_featur_01de2601-3f08-48d9-8bf6-319a0585b4b5_3-IG0UkclhtavmkpX4WsR9UIul10u14m.png'],
  ['Rose cameo frame', 'An ivory cameo portrait framed by lush deep-red roses and antique gold.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_reate_a_romantic_vintage_sticker_featuring_an_ivor_f3b9c688-40b9-4683-908c-7ea6a2800cdd_0-fVNOShKHhUdvGtElr0zr2QWYhoPp8I.png'],
  ['Burgundy cameo', 'A classic profile cameo surrounded by a wreath of velvet roses.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_reate_a_romantic_vintage_sticker_featuring_an_ivor_f3b9c688-40b9-4683-908c-7ea6a2800cdd_1-Un1olnGsoDmiPgIgFIgrlbkt6GvFwr.png'],
  ['Rosewood medallion', 'A sculpted ivory portrait set in a richly ornamented rose frame.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_reate_a_romantic_vintage_sticker_featuring_an_ivor_f3b9c688-40b9-4683-908c-7ea6a2800cdd_2-GvLCFMz1bQ24UDGxe7R9Wxc9OyprI6.png'],
  ['Cameo collection', 'A romantic antique cameo encircled by crimson roses and gilded flourishes.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_reate_a_romantic_vintage_sticker_featuring_an_ivor_f3b9c688-40b9-4683-908c-7ea6a2800cdd_3-nqc0CiBCOwX6kBoChOcYe6WvU7SG0m.png'],
  ['Vintage vanity sheet', 'A coordinated sheet of mirrors, lipstick, perfume, pearls, and keepsake boxes.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_a_coordinated_sticker_sheet_inspired_by_vin_4444e667-261d-4ed7-9614-2d9952780ec7_0-MPBZlqPbLf2ONtwdGVFDakkEf2y7u4.png'],
  ['Ruby dressing set', 'A curated red-and-gold sticker sheet for the romantic vintage vanity.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_a_coordinated_sticker_sheet_inspired_by_vin_4444e667-261d-4ed7-9614-2d9952780ec7_1-tS9rxDFNpIxYIOCI5wCg89a5n3tNBt.png'],
  ['Garnet beauty cabinet', 'A jewel-toned arrangement of a hand mirror, cosmetics, pearls, and perfume.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_a_coordinated_sticker_sheet_inspired_by_vin_4444e667-261d-4ed7-9614-2d9952780ec7_2-a6gvrDi5BzRUkvPxlXYYKPyZEVDTNv.png'],
  ['Antique vanity essentials', 'A richly detailed collection of ruby, gold, ivory, and pearl accessories.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Create_a_coordinated_sticker_sheet_inspired_by_vin_4444e667-261d-4ed7-9614-2d9952780ec7_3-V8kOdnCRGZgdeO5PHWd1XxGEOF7m5C.png'],
  ['Sapphire winter traveler', 'A Victorian woman in embroidered midnight silk overlooking a lantern-lit Venetian canal.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Venetian%20Twilight%20in%20Sapphire%20Silk-2-JCb4Nk1uzXHdLcmKFWQUk1gMMmVoCH.png'],
  ['Parisian rose garden', 'A romantic pink gown, rose garden, fountains, and Paris at sunset.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/5d8cbd3f-294b-4d82-920c-4edf5b5d45df-MKKAt76K9b27c9Hehg2NZ51JXOhuj8.png'],
  ['Lavender letter', 'A violet-clad traveler reading a letter beside a glasshouse and pressed flowers.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/78e1096d-2a78-4420-9596-a3009402fa7c-KUg45ohK6O3pUm24Q1VtVLtmat5BME.png'],
  ['Emerald lakeside garden', 'An emerald velvet gown, alpine lake, roses, and an antique cameo.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ab077698-ef34-458d-9854-132ba891729e-NA7LRtUMgWF4ZDYhXKsXpMPFpEncBl.png'],
  ['Teal azulejo courtyard', 'A teal Victorian dress framed by patterned tile, citrus trees, and bougainvillea.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Azulejo%20Courtyard%20in%20Teal-5-yQWY4ifz1FRXZKXuDpeDoY8jRvejZN.png'],
  ['Provencal lavender romance', 'A lilac gown and wide-brimmed hat among blooming lavender terraces.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Provenc%CC%A7al%20Lavender%20Terrace%20Romance-9-uA2iCtC8kU6h3t3Dku9BxdN1O7wNOq.png'],
  ['Ruby Prague garden', 'A crimson velvet traveler overlooking Prague gardens at golden hour.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Ruby%20Gown%20in%20Prague%E2%80%99s%20Sunset%20Garden-7-F0qH5fPiN0tmeczC2ckRIHEetnsTLX.png'],
  ['Winter chateau', 'An ivory gown and burgundy cape in a snow-covered chateau garden.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Romantic%20Winter%20Cha%CC%82teau%20Garden%20Collage-4-sxb73nE80OFUc0oPla60uzusSBcitc.png'],
  ['Kyoto garden traveler', 'A plum Victorian dress beside an autumn Japanese garden and koi pond.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Vintage%20Kyoto%20Garden%20Traveler-8-hFpnJ4ByIrj3TtMqcxpOL7Z7G0YeU2.png'],
  ['Alpine winter journey', 'A sapphire-clad traveler with maps and luggage in a snowy mountain garden.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Victorian%20Alpine%20Garden%20Travel%20Collage-6-dL5gs2Lo6JIAstoELQnvKcrqdS1Z42.png'],
  ['Riviera garden romance', 'An ivory parasol gown overlooking a sunlit Mediterranean terrace.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Vintage%20Riviera%20Garden%20Romance%20Sticker-10-hFGnhmznpHMmgsWEPpA1jRA5eE5P7m.png'],
  ['Moonlit sapphire pendant', 'A silver sapphire pendant framing a moonlit winter lake and distant manor.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_Victorian_landscape_sticker_featuring_a_f_b5fbb4e6-1858-4108-b7ae-c0bf9a9a9dc0_1-qhBzEL9xESFOfmBQsDCwRKW6rIh3Bd.png'],
  ['Winter moon medallion', 'A round blue gemstone pendant with a snowy woodland estate beneath the full moon.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_Victorian_landscape_sticker_featuring_a_f_b5fbb4e6-1858-4108-b7ae-c0bf9a9a9dc0_3-gtnMxAoVZNUygdGZcxAak38iD7Jrel.png'],
  ['Sapphire lake locket', 'A delicate oval locket holding a deep-blue nocturnal river landscape.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_Victorian_landscape_sticker_featuring_a_f_b5fbb4e6-1858-4108-b7ae-c0bf9a9a9dc0_0-p9JnVlcVxAawju2W6rjTa0dzRUjT9M.png'],
  ['Blue river pendant', 'An ornate sapphire pendant with a moonlit river, pines, and glowing manor windows.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_Victorian_landscape_sticker_featuring_a_f_b5fbb4e6-1858-4108-b7ae-c0bf9a9a9dc0_2-TJKA1Wvt1Fy8iiTEhWcjQoCQvEXVuG.png'],
  ['Violet perfume flacon', 'A glowing amber perfume bottle decorated with purple violets and a satin bow.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_vintage_beauty_collectible_sticker_featur_01de2601-3f08-48d9-8bf6-319a0585b4b5_0-ncXvKfM2WqpykNVcD0lTPTFcsBjDPN.png'],
  ['Violet scent bottle', 'A rounded amber fragrance bottle nestled among fresh purple flowers.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_vintage_beauty_collectible_sticker_featur_01de2601-3f08-48d9-8bf6-319a0585b4b5_3-W3RxX9P7t7r9R4902K0OHp3FqOW3PV.png'],
  ['Golden violet perfume', 'A classic golden perfume bottle with a ribbon and violet blossoms.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_vintage_beauty_collectible_sticker_featur_01de2601-3f08-48d9-8bf6-319a0585b4b5_2-RQuSfsUO4xRTMIi2KepgYfOdyTvyMx.png'],
  ['Amber bow perfume', 'An amber glass perfume bottle tied with an ivory bow and purple flowers.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_vintage_beauty_collectible_sticker_featur_01de2601-3f08-48d9-8bf6-319a0585b4b5_1-Iw8YB6hm0SmSQGDMr5XR5EX7x1hRE3.png'],
  ['Gilded garden station', 'A vintage glasshouse station surrounded by flowers, steam, and a traveling woman.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_vintage_travel_sticker_featuring_a_small__9571911d-3382-4e1d-b5fb-feabf0a7f7a0_0-3q8rTBiGyEiAeCIP4M8efre4jjOntG.png'],
  ['Glasshouse railway garden', 'A lush conservatory garden with a steam train and a teal-clad traveler.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_vintage_travel_sticker_featuring_a_small__9571911d-3382-4e1d-b5fb-feabf0a7f7a0_2-DdElz0m4L06qhymhnDleaVCdjGaDOS.png'],
  ['Flower station journey', 'A sunlit botanical railway platform with a traveler carrying flowers and luggage.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_vintage_travel_sticker_featuring_a_small__9571911d-3382-4e1d-b5fb-feabf0a7f7a0_3-EP0oyOrcqYp45VfP8UHUUu5gkV0nXu.png'],
  ['Sapphire crescent charm', 'A celestial gold crescent charm set with vivid blue stones and dangling stars.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_vintage-inspired_celestial_sticker_featur_3f3e7432-68c7-48cb-9468-13ca01827d2a_1-fHDHrMraMNiV91IoOasyH3TzNdhavp.png'],
  ['Starfall crescent', 'A gold crescent ornament with sapphire stones, ribbons, and hanging stars.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_vintage-inspired_celestial_sticker_featur_3f3e7432-68c7-48cb-9468-13ca01827d2a_3-rSULzcCoVNVPIywBHXdv0P8XOIXBwI.png'],
  ['Royal sapphire crescent', 'An elaborate crescent jewel with blue gems, ivory ribbon, and star drops.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_vintage-inspired_celestial_sticker_featur_3f3e7432-68c7-48cb-9468-13ca01827d2a_2-U4IKDYkc37uqSb35IO6Am4Hdhvmkpr.png'],
  ['Midnight crescent jewel', 'A sapphire-and-gold crescent charm set against a rich midnight background.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_a_vintage-inspired_celestial_sticker_featur_3f3e7432-68c7-48cb-9468-13ca01827d2a_0-kbe0HuVjlatqNA39NLx56rlEGcNb6L.png'],
  ['Amethyst winter frame', 'A purple gemstone frame opening onto a dreamy lavender winter forest.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_an_immersive_landscape_sticker_showing_a_wi_4f323b44-f517-491d-b355-a2b8900eadf9_0-Z05yKj9fhqtdZ5c0vcgIUGfGFU4kqD.png'],
  ['Violet forest portal', 'An ornate amethyst arch framing a luminous purple woodland path.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yess_27737_Design_an_immersive_landscape_sticker_showing_a_wi_4f323b44-f517-491d-b355-a2b8900eadf9_1-an0VBjGhPJZr92M0b5ED6wTco2G9PZ.png'],
] as const

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [focus, setFocus] = useState<'atelier' | 'jewelry' | 'journal'>('atelier')
  const [placed, setPlaced] = useState<string[]>([])
  const [selectedItem, setSelectedItem] = useState<(typeof jewelry)[number] | null>(null)

  const addSticker = (name: string) => setPlaced((items) => items.includes(name) ? items : [...items, name])
  const resetJournal = () => setPlaced([])

  return (
    <main className="atelier sticker-collection min-h-screen overflow-hidden bg-[#ede2cf] text-[#30231f]">
      <header className="relative z-20 mx-auto flex max-w-7xl items-center justify-between border-b border-[#7e2330]/30 px-6 py-5 lg:px-10">
        <a href="#top" className="brand font-display text-xl font-semibold tracking-[.08em]" aria-label="Yessy's Vintage Finds home">Yessy&apos;s <span>Vintage Finds</span></a>
        <nav className={`${menuOpen ? 'flex' : 'hidden'} absolute left-5 right-5 top-20 flex-col gap-5 border border-[#7e2330]/20 bg-[#f8f0df] p-6 shadow-xl md:static md:flex md:flex-row md:items-center md:gap-8 md:border-0 md:bg-transparent md:p-0 md:shadow-none`}>
          <a href="#jewelry" onClick={() => setMenuOpen(false)}>Jewelry cabinet</a><a href="#scrapbook" onClick={() => setMenuOpen(false)}>Sticker scrapbook</a><a href="#about" onClick={() => setMenuOpen(false)}>The story</a>
        </nav>
        <button className="rounded-sm border border-[#7e2330]/30 p-2 md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close menu' : 'Open menu'}>{menuOpen ? <X /> : <Menu />}</button>
      </header>

      <section id="top" className="mx-auto grid max-w-7xl items-center gap-10 px-6 py-14 lg:grid-cols-[.76fr_1.24fr] lg:px-10 lg:py-20">
        <div className="relative z-10"><p className="eyebrow">An independent vintage seller</p><h1 className="font-display mt-5 max-w-xl text-6xl font-medium leading-[.94] sm:text-8xl">Step inside a world of <em>timeless treasures.</em></h1><p className="mt-7 max-w-md text-lg leading-8 text-[#624b42]">A lovingly curated cabinet of vintage Avon jewelry and paper curiosities, gathered for the modern collector.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#jewelry" className="button button-primary">Explore Jewelry <ArrowDown /></a><a href="#scrapbook" className="button button-outline">Discover Stickers <ArrowUpRight /></a></div></div>
        <div className="relative overflow-hidden rounded-[2rem] border border-[#7e2330]/25 bg-[#d8c6aa] p-3 shadow-[0_24px_70px_rgba(48,35,31,.2)]"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Venetian%20Twilight%20in%20Sapphire%20Silk-2-JCb4Nk1uzXHdLcmKFWQUk1gMMmVoCH.png" alt="Victorian traveler in sapphire silk beside a snowy alpine garden" className="max-h-[760px] w-full rounded-[1.5rem] object-contain" /><div className="absolute bottom-8 left-8 bg-[#f8f0df]/90 px-4 py-3 text-xs uppercase tracking-[.18em] text-[#7e2330]">Featured collection · Sapphire winter travel</div></div>
      </section>

      <section className="mx-auto grid max-w-7xl gap-6 border-y border-[#7e2330]/25 px-6 py-7 sm:grid-cols-3 lg:px-10"><div><span className="number">01</span><h2>Collected with care</h2><p>Authentic vintage pieces, clearly described.</p></div><div><span className="number">02</span><h2>A slower kind of shopping</h2><p>Details, patina, and stories worth noticing.</p></div><div><span className="number">03</span><h2>Always independent</h2><p>Concept imagery is labeled; information is editable.</p></div></section>

      <section id="jewelry" className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><div className="section-heading"><div><p className="eyebrow">The Victorian sticker collection</p><h2 className="font-display">Die-cut ladies in emerald velvet.</h2></div><p>A quartet of luxurious Victorian portrait stickers, made for winter journals, gift wrap, and collectors of beautiful paper curiosities.</p></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{jewelry.map(([name, meta, description, image], index) => <article className="product-card" key={name}><div className={`jewel jewel-${index + 1}`}><img src={image} alt={name} /></div><p className="eyebrow mt-5">{meta}</p><h3 className="font-display mt-2 text-2xl">{name}</h3><p className="mt-2 text-sm leading-6 text-[#624b42]">{description}</p><button type="button" onClick={() => setSelectedItem([name, meta, description, image])} className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-[#7e2330] underline underline-offset-4">View details</button></article>)}</div></section>

      {selectedItem && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#30231f]/70 p-6" role="dialog" aria-modal="true" aria-labelledby="item-detail-title"><div className="relative grid max-w-2xl gap-6 bg-[#f8f0df] p-5 shadow-2xl sm:grid-cols-2"><button type="button" onClick={() => setSelectedItem(null)} className="absolute right-3 top-3 rounded-full bg-[#f8f0df] p-2 text-[#7e2330]" aria-label="Close item details"><X /></button><img src={selectedItem[3]} alt={selectedItem[0]} className="h-full min-h-64 w-full object-cover" /><div className="flex flex-col justify-center pr-4"><p className="eyebrow">{selectedItem[1]}</p><h2 id="item-detail-title" className="font-display mt-3 text-4xl">{selectedItem[0]}</h2><p className="mt-4 leading-7 text-[#624b42]">{selectedItem[2]}</p><button type="button" onClick={() => setSelectedItem(null)} className="button button-primary mt-6 self-start">Close details <X /></button></div></div></div>}

      <section className="mx-auto max-w-7xl border-t border-[#7e2330]/25 px-6 py-20 lg:px-10"><div className="section-heading"><div><p className="eyebrow">The complete image cabinet</p><h2 className="font-display">Every collected scene, kept together.</h2></div><p>The original atelier studies and the newest winter fashion stickers now live in one growing visual archive.</p></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{archiveImages.map(([name, description, image]) => <article key={name} className="product-card group"><div className="jewel"><img src={image} alt={name} /></div><h3 className="font-display mt-5 text-2xl">{name}</h3><p className="mt-2 text-sm leading-6 text-[#624b42]">{description}</p></article>)}</div></section>

      <section id="scrapbook" className="scrapbook-wrap mx-auto max-w-7xl px-6 py-10 lg:px-10"><div className="section-heading"><div><p className="eyebrow">The traveling scrapbook</p><h2 className="font-display">Make a page of your own.</h2></div><p>Tap a sticker to place it on the journal. The samples are conceptual imagery, ready to be swapped for your collection.</p></div><div className="mt-10 grid gap-8 lg:grid-cols-[.72fr_1.28fr] lg:items-center"><div className="sticker-tray">{stickerNames.map((name, index) => <button key={name} onClick={() => addSticker(name)} className={`sample-sticker sticker-${index + 1}`} aria-label={`Place ${name} sticker`}>{name}</button>)}<p className="mt-8 text-center text-xs uppercase tracking-[.18em] text-[#f8f0df]/70">Tap to collect</p></div><div className="journal"><div className="journal-header"><span>Travel notes · vol. 12</span><button onClick={resetJournal} aria-label="Reset journal composition"><RotateCcw /></button></div><div className="journal-page"><p className="font-display text-3xl italic text-[#7e2330]">Souvenirs from<br />somewhere lovely</p><p className="mt-3 max-w-xs text-sm leading-6 text-[#624b42]">A page for pressed flowers, perfume labels, and places I mean to return to.</p>{placed.map((name, index) => <span key={name} className={`placed-sticker placed-${index + 1}`}>{name}</span>)}{placed.length === 0 && <span className="journal-hint">Your collected stickers will appear here.</span>}</div></div></div></section>

      <section id="about" className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><div className="about-card"><p className="eyebrow">A note from the cabinet</p><h2 className="font-display mt-4 text-5xl">For the romantics, collectors, and curious.</h2><p className="mt-5 max-w-2xl leading-8 text-[#624b42]">Yessy&apos;s Vintage Finds is an independent seller celebrating the beauty of old things: a clasp with a little wear, a brooch that remembers an evening, a paper sticker that makes a blank page feel like a journey. Product information is intentionally editable for your real inventory.</p></div></section>

      <footer className="mx-auto flex max-w-7xl flex-col gap-3 border-t border-[#7e2330]/30 px-6 py-8 text-sm sm:flex-row sm:justify-between lg:px-10"><span className="brand font-display">Yessy&apos;s Vintage Finds</span><span>Conceptual imagery · Independent seller</span><a href="mailto:hello@yessysvintage.com">hello@yessysvintage.com</a></footer>
    </main>
  )
}

function AtelierScene({ focus, onFocus }: { focus: string; onFocus: (focus: 'atelier' | 'jewelry' | 'journal') => void }) {
  return <div className={`scene scene-${focus}`} role="img" aria-label="Interactive vintage atelier with a jewelry tray and travel journal"><div className="mirror"><span>YV</span></div><div className="table"><button className="tray" onClick={() => onFocus('jewelry')} aria-label="Focus on jewelry tray"><span className="brooch">✦</span><span className="pearl pearl-a" /><span className="pearl pearl-b" /><small>Jewelry cabinet</small></button><button className="journal-object" onClick={() => onFocus('journal')} aria-label="Focus on travel journal"><span>Travel<br />notes</span></button><div className="vase">❀</div></div><div className="scene-caption"><Sparkles />{focus === 'atelier' ? 'Select an object to explore' : focus === 'jewelry' ? 'Jewelry collection' : 'Sticker scrapbook'}</div></div>
}
